language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install pygame
    - pip install requests
script: nosetests -v && flake8 *.py --max-line-length=110
